spring:
  application:
    name: gatewayserver
  config:
    import: optional:configserver:http://localhost:8070
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: false

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8072